---
- name: Configure Linux Server
  hosts: "{{ targeted_hosts }}"  
  # This will use the value from the survey or 'all' if no value is provided.
  become: true
  gather_facts: no
  vars_files:
    - envs/dev/group_vars/vars.yml
  # Dynamically apply tags from the survey
  tags: "{{ selected_tags | flatten }}"

  roles:
  - role: files_creation
  - role: packages_install


# A whole role can't be tagged, but if we want a whole 
# role to be executed how to achieve that using tags?
#######################################################
# The solution is that we specify a tag for the 
# role and repeat it in all tasks in the role.