---
- name: Ensure EPEL repository is enabled (required for nginx)
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install NGINX
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Start and enable NGINX
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy NGINX proxy configuration
  ansible.builtin.template:
    src: nginx-proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart NGINX