---
- name: Ensure EPEL repository is enabled
  yum:
    name: epel-release
    state: present

- name: Install common packages
  package:
    name: "{{ packages }}"
    state: present

- name: Update all system packages to the latest version
  yum:
    name: "*"
    state: latest

- name: Set the timezone to Europe/London
  command: timedatectl set-timezone Europe/London