files:
  - name: "file1.txt"
    path: "/tmp/file1.txt"
  - name: "file2.txt"
    path: "/tmp/file2.txt"

packages:
  - tar
  - zip
  - unzip
  - bash-completion
  - htop
  - tree
  - ncdu
  - iotop
  - iftop
  - lsof
  - sysstat

users:
  - jeromeseguin
  - briancollins
  - mohamedsallami
  - geoffcamp
  - mounireldhimni
  - guillaumejuncker