---
- name: Ensure repository is enabled (equivalent to EPEL on Debian-based systems)
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ focal main universe'
    state: present
  tags:
    - packages
    - packages_vars

- name: Install common packages
  package:
    name: "{{ packages }}"
    state: present
  tags:
    - packages
    - packages_vars

- name: Update all system packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    state: latest
  tags:
    - packages
    - packages_vars
    - packages_update
