---
- name: Ensure the repository is enabled (required for nginx)
  ansible.builtin.apt_repository:
    repo: 'deb http://nginx.org/packages/debian/ stable nginx'
    state: present
  tags:
    - packages_install
    - nginx_install_config
    - nginx_repo

- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present
  tags:
    - packages_install
    - nginx_install_config
    - nginx_install

- name: Start and enable NGINX
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  tags:
    - packages_install
    - nginx_install_config
    - nginx_start_enable

- name: Deploy NGINX proxy configuration
  ansible.builtin.template:
    src: nginx-proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart NGINX
  tags:
    - packages_install
    - nginx_install_config
    - nginx_restart