---
- name: Ensure repository is enabled (equivalent to EPEL on Debian-based systems)
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ focal main universe'
    state: present
  tags:
    - packages_install
    - packages_vars
    - apt_repo

- name: Install common packages
  package:
    name: "{{ packages }}"
    state: present
  tags:
    - packages_install
    - packages_vars
    - packages_vars_install

- name: Update all system packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    state: latest
  tags:
    - packages_install
    - packages_vars
    - packages_update

- name: Set the timezone to Europe/London
  command: timedatectl set-timezone Europe/London
  tags:
    - packages_install
    - packages_install_vars
    - timezone
